
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavUI from "./compements/navbar/NavUI";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  Navbar
}: {
    children: React.ReactNode;
    Navbar:JSX.Element
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavUI cartItemsCount={9} />
        {children}
        <h1 className="text-2xl">Footer</h1>
      </body>
    </html>
  );
}
